name: Audit Dependencies

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-install-check:
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse:4.1.0
    name: oysteR scan

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: install.packages("oysteR", repos="http://cran.us.r-project.org")
        shell: Rscript {0}

      - name: Run oysteR scan on dependencies
        run: |
          dependencies_scan = oysteR::audit_description(
            dir = ".",
            fields = c("Depends", "Imports", "Suggests"),
            verbose = TRUE
          )
          print(as.data.frame(dependencies_scan[c("package", "version", "vulnerabilities", "no_of_vulnerabilities")]))
        shell: Rscript {0}

      - name: Run oysteR scan on renv.lock
        run: |
          if (file.exists("renv.lock")) {
            renv_lock_scan = oysteR::audit_renv_lock(dir = ".", verbose = TRUE)
            print(as.data.frame(renv_lock_scan[c("package", "version", "vulnerabilities", "no_of_vulnerabilities")]))
          } else {
            print("No renv.lock file, not scanning.")
          }
        shell: Rscript {0}
