name: R CMD Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-install-check:
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.config.image }}:${{ matrix.config.tag }}
    name: ${{ matrix.config.image }}, version ${{ matrix.config.tag }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {image: rocker/tidyverse, tag: '3.6.3'}
          - {image: rocker/tidyverse, tag: '4.1.0'}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          path: ${{ github.event.repository.name }}

      - name: Install dependencies
        run: |
          setwd("${{ github.event.repository.name }}")
          options(repos = c(CRAN = "https://cloud.r-project.org/"))
          if (file.exists("renv.lock")) {
            renv::restore()
          } else {
             "remotes" %in% installed.packages() || install.packages("remotes", upgrade = "never")
            remotes::install_deps(dependencies = TRUE, upgrade = "never")
          }
        shell: Rscript {0}

      - name: Build R package
        run: |
          R CMD build ${{ github.event.repository.name }}
          echo "PKGBUILD=$(echo *.tar.gz)" >> $GITHUB_ENV
        shell: bash

      - name: Run R CMD CHECK
        id: check
        run: |
          R CMD check --no-manual ${{ env.PKGBUILD }}
          # https://trstringer.com/github-actions-multiline-strings/
          output=$(cat ${{ github.event.repository.name }}.Rcheck/00check.log)
          output="${output//'%'/'%25'}"
          output="${output//$'\n'/'%0A'}"
          output="${output//$'\r'/'%0D'}"
          echo "::set-output name=check-output::$output"
        shell: bash

      - name: Post check output as comment
        uses: actions/github-script@v4
        with:
          script: |
            const output = `<details><summary>R CMD Check Output for R ${{ matrix.config.tag }}</summary>

            \`\`\`R
            ${{ steps.check.outputs.check-output }}
            \`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Catch warnings in R CMD check output
        run: |
          x <- tail(readLines("${{ github.event.repository.name }}.Rcheck/00check.log"), 1)
          if (!grepl("^Status", x)) stop("No status line found in R CMD check log")
          if (grepl("WARNINGs", x)) stop("R CMD check has warnings")
        shell: Rscript {0}

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.config.tag }}-results
          path: ${{ github.event.repository.name }}.Rcheck/00check.log

      - name: Install R package
        run: R CMD INSTALL ${{ env.PKGBUILD }}
        shell: bash
