name: R CMD Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-install-check:
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.config.image }}:${{ matrix.config.tag }}
    name: ${{ matrix.config.image }}, version ${{ matrix.config.tag }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {image: rocker/tidyverse, tag: '3.6.3'}
          - {image: rocker/tidyverse, tag: '4.1.0'}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: remotes::install_cran(pkgs = c("tinytest", "knitr"))
        shell: Rscript {0}

      - name: Build R package
        run: |
          R CMD build .
          echo "PKGBUILD=$(echo *.tar.gz)" >> $GITHUB_ENV
        shell: bash

      - name: Install R package
        run: R CMD INSTALL ${{ env.PKGBUILD }}
        shell: bash

      - name: Run R CMD Check
        run: R CMD check --no-manual ${{ env.PKGBUILD }} --output check
        shell: bash

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name:  ${{ matrix.config.image }}:${{ matrix.config.tag }}-results
          path: check
