name: License report

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  license:
    runs-on: ubuntu-latest
    name: Generate

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: License report
        uses: ./.github/actions/license-report
