name: Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint codebase
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse:3.6.3
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install package
        run: R CMD INSTALL .

      - name: Run lintr
        run: lintr::lint_package()
        shell: Rscript {0}
