name: Docs

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  pkgdown:
    name: Generate
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse:3.6.3
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          if (file.exists("renv.lock")) {
            renv::restore()
          } else {
            options(repos = c(CRAN = "https://cloud.r-project.org/"))
            "remotes" %in% installed.packages() || install.packages("remotes", upgrade = "never")
            remotes::install_deps(dependencies = TRUE, upgrade = "never")
          }
        shell: Rscript {0}

      - name: Install Respectables
        run: R CMD INSTALL .
        shell: bash

      - name: Build docs
        run: |
          options(repos = c(CRAN = "https://cloud.r-project.org/"))
          "pkgdown" %in% installed.packages() || install.packages("pkgdown", upgrade = "never")
          pkgdown::build_site(".", devel = TRUE)
        shell: Rscript {0}

      - name: Upload docs for review
        if: github.ref != 'refs/heads/master' # Only during PR
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: docs/

      - name: Publish docs
        if: github.ref == 'refs/heads/master' # Only after merge or push to master
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
