name: Docs

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  pkgdown:
    name: Generate
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse:3.6.3
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Build docs
        run: R -e 'pkgdown::build_site(".", devel = FALSE)' | tee pkgdown.out
        shell: bash

      - name: Upload pkgdown output
        uses: actions/upload-artifact@v2
        with:
          name: pkgdown.out
          path: pkgdown.out

      - name: Upload docs for review
        if: github.ref != 'refs/heads/master' # Only during PR
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: docs/

      - name: Publish docs
        if: github.ref == 'refs/heads/master' # Only after merge or push to master
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
