name: TODOs

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  todos:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Generate TODO list
        run: grep -R -A 2 "TODO" R/ > TODOs.txt
        shell: bash

      - name: Upload TODO list
        uses: actions/upload-artifact@v2
        with:
          name: TODOs.txt
          path: TODOs.txt
